### ISSUE TITLE
Segmentaion error when entering wrong credentials or server is down

### ISSUE THREAD

**Issue by nourmat** [etesync/etesync-rs#1] opened 2020-05-19 14:39 UTC
From what I understand "etesync_set_auth_token" opens the session for the API to a specific user (as token is calculated using username and password), if the server is down or the url is wrong or the token was calculated wrong (wrong credentials) it gives Segmentaion error and it shouldn't segfault.

I reproduce this just by running the example.c with wrong password and another time with server down and once with wrong url

**Comment by tasn** [comment] 2020-06-07 15:43
Just documenting my thoughts: we'll probably add an `errno`-like solution for error reporting since all of our APIs should return a value that can be checked for errors.
In the meanwhile, just make sure your code doesn't error. :P

**Comment by tasn** [comment] 2020-06-09 08:33
I can't reproduce it. It doesn't segfault here. I added more tests to verify, but things seem fine.

**Comment by nourmat** [comment] 2020-06-09 13:02
Hey, tasn. you're right I wasn't checking if token returned null or not, this was a problem.
And as for the encryption_password I need to check if keypair also returned null or not. 
Guess that solved the problem :D
Thank you and sorry for the inconvenience.
should I close the issue now? :/

**Comment by tasn** [comment] 2020-06-09 13:07
Closed in favour of #4, as there's still something that needs fixing (getting the error information), but this ticket is invalid.

**Closed** 2020-06-09 13:08 UTC
